### ISSUE TITLE
what is the license of this repository?

### ISSUE THREAD

**Issue by ghost** [RobertixCZ/Robertix_CZ-Photography#1]
Hi.

I would like to know what is the license of this repository. What is the license of this repository? Is MIT? GPL? Unlicensed? (I would like to use the repository for something I'm doing, creating)

**Comment by RobertixCZ** [comment]
Hi,

my repository was made as a school project website from a YouTube tutorial,
so it's made out of a non-copyright source.

If you want to remake it to your own website, I have no problem with that.
Just please don't use my photos anywhere else. Thanks

Sincerely,

Robertix_CZ

Dne ne 5. 3. 2023 20:30 uživatel villenmarx ***@***.***>
napsal:

**Comment by ghost** [comment]
> Hi,
> my repository was made as a school project website from a YouTube tutorial,
> so it's made out of a non-copyright source.

thanks for comment!

> If you want to remake it to your own website, I have no problem with that.

What do you think of this idea? (please, see this: `https://randommachine.github.io/graph/` )

> Just please don't use my photos anywhere else. Thanks

Can I keep the text on the site? Or should I also remove? 

> Sincerely,
> Robertix_CZ

thanks for comment!
